name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Mantenha 'main' ou mude para 'master'

jobs:
  # O primeiro 'job' (trabalho) sobe o seu arquivo como um artefato.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build and Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # O ponto indica que ele deve subir a pasta raiz do seu projeto

  # O segundo 'job' (trabalho) pega o artefato e faz o deploy.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
